export const dataAssistant = [
  {
    kepalaLab: {
      id: "1",
      image: "https://www.linkpicture.com/q/pakyudi.png",
      role: "Kepala Laboratorium",
      name: "Yudi Irawan Chandra S.kom,MMsi",
      date: "2018 - Sekarang",
    },
    assistan: [
      {
        id: "2",
        image: "https://www.linkpicture.com/q/daffa.png",
        role: "Staff Laboratorium",
        name: "Daffa Reyhan",
        date: "2020 - Sekarang",
      },
      {
        id: "3",
        image: "https://www.linkpicture.com/q/clarissa.png",
        role: "Staff Laboratorium",
        name: "Clarissa Cahya N",
        date: "2020 - Sekarang",
      },
      {
        id: "4",
        image: "https://www.linkpicture.com/q/fakhri.png",
        role: "Staff Laboratorium",
        name: "Fakhri Haromain",
        date: "2021 - Sekarang",
      },
      {
        id: "5",
        image: "https://www.linkpicture.com/q/anisya.png",
        role: "Asisten Aktif",
        name: "Anisya Komalasari",
        date: "2020 - Sekarang",
      },
      {
        id: "6",
        image: "https://www.linkpicture.com/q/fitri.png",
        role: "Asisten Aktif",
        name: "Fitri Nurhikmah",
        date: "2020 - Sekarang",
      },
      {
        id: "7",
        image: "https://www.linkpicture.com/q/dinda.png",
        role: "Asisten Aktif",
        name: "Dinda Nurazizah",
        date: "2020 - Sekarang",
      },
      {
        id: "8",
        image: "https://www.linkpicture.com/q/inna.png",
        role: "Asisten Aktif",
        name: "Inna Soviyati",
        date: "2020 - Sekarang",
      },
      {
        id: "9",
        image: "https://www.linkpicture.com/q/fahri.png",
        role: "Asisten Aktif",
        name: "Fahri Alfiansyah",
        date: "2020 - Sekarang",
      },
      {
        id: "10",
        image: "https://www.linkpicture.com/q/jeki.png",
        role: "Asisten Aktif",
        name: "Rizaki Fadhilla F",
        date: "2021 - Sekarang",
      },
      {
        id: "11",
        image: "https://www.linkpicture.com/q/nazul.png",
        role: "Asisten Aktif",
        name: "Naza Zulfiqi",
        date: "2021 - Sekarang",
      },
      {
        id: "12",
        image: "https://www.linkpicture.com/q/zidane.png",
        role: "Asisten Aktif",
        name: "Zidane Arvito",
        date: "2021 - Sekarang",
      },
      {
        id: "13",
        image: "https://www.linkpicture.com/q/sani.png",
        role: "Asisten Aktif",
        name: "Ilham Sani",
        date: "2021 - Sekarang",
      },
      {
        id: "14",
        image: "https://www.linkpicture.com/q/azkia.png",
        role: "Asisten Aktif",
        name: "Nur Azkia Rahmah",
        date: "2021 - Sekarang",
      },
      {
        id: "15",
        image: "https://www.linkpicture.com/q/mutsol.png",
        role: "Asisten Aktif",
        name: "Muthia Solikin",
        date: "2021 - Sekarang",
      },
      {
        id: "16",
        image: "https://www.linkpicture.com/q/radhya.png",
        role: "Asisten Aktif",
        name: "Radhya Anindita",
        date: "2021 - Sekarang",
      },
      {
        id: "17",
        image: "https://www.linkpicture.com/q/azz.png",
        role: "Asisten Aktif",
        name: "Azizah D. Juniasari",
        date: "2021 - Sekarang",
      },
      {
        id: "18",
        image: "https://www.linkpicture.com/q/putri.png",
        role: "Asisten Aktif",
        name: "Putri Rahmawati",
        date: "2022 - Sekarang",
      },
      {
        id: "19",
        image: "https://www.linkpicture.com/q/dea.png",
        role: "Asisten Aktif",
        name: "Dea Ainun Latifah",
        date: "2022 - Sekarang",
      },
      {
        id: "20",
        image: "https://www.linkpicture.com/q/icang.png",
        role: "Asisten Aktif",
        name: "Annisa Ramadhani",
        date: "2022 - Sekarang",
      },
      {
        id: "21",
        image: "https://www.linkpicture.com/q/dzaki.png",
        role: "Asisten Aktif",
        name: "Dzaki Farizqi",
        date: "2022 - Sekarang",
      },
      {
        id: "22",
        image: "https://www.linkpicture.com/q/fikri.png",
        role: "Asisten Aktif",
        name: "Fikri Kamal",
        date: "2022 - Sekarang",
      },
    ],
  },
];
