export const dataAssistant = [
  {
    kepalaLab: {
      id: "1",
      image: "/assets/images/struktur/pakyudi.png",
      role: "Kepala Laboratorium",
      name: "Yudi Irawan Chandra S.kom,MMsi",
      date: "2018 - Sekarang",
    },
    assistan: [
      {
        id: "2",
        image: "/assets/images/struktur/putri.png",
        role: "Staff Laboratorium",
        name: "Putri Rahmawati",
        date: "2022 - Sekarang",
      },
      {
        id: "3",
        image: "/assets/images/struktur/fikri.png",
        role: "Staff Laboratorium",
        name: "Fikri Kamal",
        date: "2022 - Sekarang",
      },
      {
        id: "4",
        image: "/assets/images/struktur/agung.png",
        role: "Staff Laboratorium",
        name: "Agung Nugroho",
        date: "2023 - Sekarang",
      },
      {
        id: "5",
        image: "/assets/images/struktur/dea.png",
        role: "Asisten Aktif",
        name: "Dea Ainun Latifah",
        date: "2022 - Sekarang",
      },
      {
        id: "6",
        image: "/assets/images/struktur/icang.png",
        role: "Asisten Aktif",
        name: "Annisa Ramadhani",
        date: "2022 - Sekarang",
      },
      {
        id: "7",
        image: "/assets/images/struktur/dzaki.png",
        role: "Asisten Aktif",
        name: "Dzaki Farizqi",
        date: "2022 - Sekarang",
      },
      {
        id: "8",
        image: "/assets/images/struktur/annisa.png",
        role: "Asisten Aktif",
        name: "Anisa Wulan Sari",
        date: "2023 - Sekarang",
      },
      {
        id: "9",
        image: "/assets/images/struktur/azziizah.png",
        role: "Asisten Aktif",
        name: "Nur Rahmah Aziizah",
        date: "2023 - Sekarang",
      },
      {
        id: "10",
        image: "/assets/images/struktur/anandita.png",
        role: "Asisten Aktif",
        name: "Anandita Rizkia",
        date: "2023 - Sekarang",
      },
      {
        id: "11",
        image: "/assets/images/struktur/rafta.png",
        role: "Asisten Aktif",
        name: "Muhammad Rafta Rizky",
        date: "2023 - Sekarang",
      },
      {
        // data anak lama
        id: "12",
        image: "/assets/images/struktur/daffa.png",
        role: "Asisten Aktif",
        name: "Muhammad Daffa Riyanto",
        date: "2023 - Sekarang",
      },
      {
        id: "13",
        image: "/assets/images/struktur/hilham.png",
        role: "Asisten Aktif",
        name: "Hilham Yulistio",
        date: "2023 - Sekarang",
      },
      {
        id: "14",
        image: "/assets/images/struktur/aiesha.png",
        role: "Asisten Aktif",
        name: "Aieshe Phoebe A.",
        date: "2024 - Sekarang",
      },
      {
        id: "15",
        image: "/assets/images/struktur/artha.png",
        role: "Asisten Aktif",
        name: "Artha Graceva",
        date: "2024 - Sekarang",
      },
      {
        id: "16",
        image: "/assets/images/struktur/atifah.png",
        role: "Asisten Aktif",
        name: "Atifah Khairunnisa",
        date: "2024 - Sekarang",
      },
      {
        id: "17",
        image: "/assets/images/struktur/indah.png",
        role: "Asisten Aktif",
        name: "Indah Faradila",
        date: "2024 - Sekarang",
      },
      {
        id: "18",
        image: "/assets/images/struktur/laura.png",
        role: "Asisten Aktif",
        name: "Laura Alysa N.T.",
        date: "2024 - Sekarang",
      },
      {
        id: "19",
        image: "/assets/images/struktur/dzakwan.png",
        role: "Asisten Aktif",
        name: "Dzakwan Saputra",
        date: "2024 - Sekarang",
      },
      {
        id: "20",
        image: "/assets/images/struktur/fiqih.png",
        role: "Asisten Aktif",
        name: "Ahmad Fiqih",
        date: "2024 - Sekarang",
      },
      {
        id: "21",
        image: "/assets/images/struktur/iman.png",
        role: "Asisten Aktif",
        name: "Imanuel Yehezkiel S.",
        date: "2024 - Sekarang",
      },
      // {
      //   id: "23",
      //   image: "",
      //   role: "",
      //   name: "",
      //   date: "",
      // },
    ],
  },
];
