export const dataAssistant = [
  {
    kepalaLab: {
      id: "1",
      image: "/assets/images/struktur/pakyudi.png",
      role: "Kepala Laboratorium",
      name: "Yudi Irawan Chandra S.kom,MMsi",
      date: "2018 - Sekarang",
    },
    assistan: [
      {
        id: "2",
        image: "/assets/images/struktur/fakhri.png",
        role: "Staff Laboratorium",
        name: "M Fakhri Haromain",
        date: "2021 - Sekarang",
      },
      {
        id: "3",
        image: "/assets/images/struktur/putri.png",
        role: "Staff Laboratorium",
        name: "Putri Rahmawati",
        date: "2022 - Sekarang",
      },
      {
        id: "4",
        image: "/assets/images/struktur/nazul.png",
        role: "Staff Laboratorium",
        name: "Naza Zulfiqi",
        date: "2021 - Sekarang",
      },
      {
        id: "5",
        image: "/assets/images/struktur/jeki.png",
        role: "Asisten Aktif",
        name: "Rizaki Fadhilla F",
        date: "2021 - Sekarang",
      },
      {
        id: "6",
        image: "/assets/images/struktur/zidane.png",
        role: "Asisten Aktif",
        name: "Zidane Arvito",
        date: "2021 - Sekarang",
      },
      {
        id: "7",
        image: "/assets/images/struktur/sani.png",
        role: "Asisten Aktif",
        name: "Ilham Sani",
        date: "2021 - Sekarang",
      },
      {
        id: "8",
        image: "/assets/images/struktur/azkia.png",
        role: "Asisten Aktif",
        name: "Nur Azkia Rahmah",
        date: "2021 - Sekarang",
      },
      {
        id: "9",
        image: "/assets/images/struktur/mutsol.png",
        role: "Asisten Aktif",
        name: "Muthia Solikin",
        date: "2021 - Sekarang",
      },
      {
        id: "10",
        image: "/assets/images/struktur/radhya.png",
        role: "Asisten Aktif",
        name: "Radhya Anindita",
        date: "2021 - Sekarang",
      },
      {
        id: "11",
        image: "/assets/images/struktur/azz.png",
        role: "Asisten Aktif",
        name: "Azizah D. Juniasari",
        date: "2021 - Sekarang",
      },
      {
        id: "12",
        image: "/assets/images/struktur/dea.png",
        role: "Asisten Aktif",
        name: "Dea Ainun Latifah",
        date: "2022 - Sekarang",
      },
      {
        id: "13",
        image: "/assets/images/struktur/icang.png",
        role: "Asisten Aktif",
        name: "Annisa Ramadhani",
        date: "2022 - Sekarang",
      },
      {
        id: "14",
        image: "/assets/images/struktur/dzaki.png",
        role: "Asisten Aktif",
        name: "Dzaki Farizqi",
        date: "2022 - Sekarang",
      },
      {
        id: "15",
        image: "/assets/images/struktur/fikri.png",
        role: "Asisten Aktif",
        name: "Fikri Kamal",
        date: "2022 - Sekarang",
      },
      {
        id: "16",
        image: "/assets/images/struktur/annisa.png",
        role: "Asisten Aktif",
        name: "Anisa Wulan Sari",
        date: "2023 - Sekarang",
      },
      {
        id: "17",
        image: "/assets/images/struktur/putrifeb.png",
        role: "Asisten Aktif",
        name: "Putri Febriyani",
        date: "2023 - Sekarang",
      },
      {
        id: "18",
        image: "/assets/images/struktur/anandita.png",
        role: "Asisten Aktif",
        name: "Anandita Rizkia",
        date: "2023 - Sekarang",
      },
      {
        id: "19",
        image: "/assets/images/struktur/azziizah.png",
        role: "Asisten Aktif",
        name: "Nur Rahmah Aziizah",
        date: "2023 - Sekarang",
      },
      {
        id: "20",
        image: "/assets/images/struktur/rafta.png",
        role: "Asisten Aktif",
        name: "Muhammad Rafta Rizky",
        date: "2023 - Sekarang",
      },
      {
        id: "21",
        image: "/assets/images/struktur/daffa.png",
        role: "Asisten Aktif",
        name: "Muhammad Daffa Riyanto",
        date: "2023 - Sekarang",
      },
      {
        id: "22",
        image: "/assets/images/struktur/hilham.png",
        role: "Asisten Aktif",
        name: "Hilham Yulistio",
        date: "2023 - Sekarang",
      },
      {
        id: "23",
        image: "/assets/images/struktur/agung.png",
        role: "Asisten Aktif",
        name: "Agung Nugroho",
        date: "2023 - Sekarang",
      },
    ],
  },
];
